{{- define "devops-test-frontend.envVariables" }}
- name: BASE_API_URL
  value: "https://devops-test-backend.devopscycle.com"
- name: BASE_APP_URL
  value: "https://devops-test-frontend.devopscycle.com"
{{- end }}