name: "Backend Pipeline"

run-name: "Backend deploy by @${{ github.actor }}"

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

on:
  workflow_dispatch: # allow trigger from github dashboard
  # push:
  #   branches:
  #     - '**'
  #   paths:
  #     - "apps/image-share-app-backend/**.**"
  #     - "ops/k8s/backend/**.**"
  #     - ".github/workflows/backendapp.yaml"

# https://docs.docker.com/build/ci/github-actions/share-image-jobs/
jobs:
  backend_build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Set up QEMU"
      uses: docker/setup-qemu-action@v2

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Login to Docker Hub"
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: "Build and export"
      uses: docker/build-push-action@v4
      with:
        context: "apps/image-share-app-backend"
        load: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-test:backend-${{ github.sha }}
        outputs: type=docker,dest=/tmp/docker.tar

    - name: "Upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: myimage
        path: /tmp/docker.tar

  backend_lint:
    name: "LINT"
    runs-on: ubuntu-latest
    needs: [backend_build]
    steps:
    - name: "Download artifact"
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp
    - name: "Load image and test"
      run: |
        docker load --input /tmp/docker.tar
        docker image ls -a
        docker run --rm --name test ${{ secrets.DOCKERHUB_USERNAME }}/devops-test:backend-${{ github.sha }} npm run lint

  backend_test:
    name: "TEST"
    runs-on: ubuntu-latest
    needs: [backend_build]
    steps:
    - name: "Download artifact"
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp
    - name: "Load image and test"
      run: |
        docker load --input /tmp/docker.tar
        docker image ls -a
        docker run --rm --name test ${{ secrets.DOCKERHUB_USERNAME }}/devops-test:backend-${{ github.sha }} npm test

  backend_remove_artifacts:
    name: "Remove Artifacts if not main branch"
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: [backend_test, backend_lint]
    steps:
    - name: "Delete Artifact"
      uses: geekyeggo/delete-artifact@v2
      with:
        name: myimage

  backend_deliver:
    name: "Deliver to Docker Hub"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [backend_build, backend_lint, backend_test]
    steps:
    - name: "Download artifact"
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp

    - name: "Login to Docker Hub"
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: "Push Image to Docker Hub"
      run: |
        docker load --input /tmp/docker.tar
        docker image ls -a
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-test:backend-${{ github.sha }}

  backend_kubernetes_deploy:
    name: "Deploy on Azure AKS"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [backend_deliver]
    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Download artifact"
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp

    - name: "Get Docker Image"
      run: |
        docker load --input /tmp/docker.tar
        docker image ls -a

    - name: "Az CLI login"
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: "Install kubectl"
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        # verify installation
        kubectl version --client

    - name: "Install helm"
      run: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update --yes
        sudo apt-get install helm  --yes

        # verify installation
        helm version

    - name: "Install azure cli"
      run: |
        # install azure cli
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        sudo apt-get update --yes
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg --yes
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
            gpg --dearmor |
            sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
            sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update --yes
        sudo apt-get install azure-cli --yes

        # verify installation
        az --version

    - name: "Install k8s credentials & switch context"
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_CLUSTER_NAME }}
        kubectl config use-context ${{ secrets.AZURE_CLUSTER_NAME }}

    - name: "Create Namespace if not exists"
      run: |
        kubectl create namespace devops-test --dry-run=client -o yaml | kubectl apply -f -

    - name: "Create kubectl secrets"
      run: |
        # https://stackoverflow.com/a/45881259/1190853
        kubectl create secret \
          generic api-secrets-devops-test \
          -n devops-test \
          --from-literal=db-user=${{ secrets.DB_USER }} \
          --from-literal=db-pass=${{ secrets.DB_PASS }} \
          --from-literal=db-host=${{ secrets.DB_HOST }} \
          --from-literal=db-port=${{ secrets.DB_PORT }} \
          --from-literal=db-name=${{ secrets.DB_NAME }} \
          --from-literal=jwt-secret=${{ secrets.JWT_SECRET }} \
          --dry-run=client -o yaml | \
            kubectl apply -f -

        # create docker registry secrets for pulling images
        kubectl create secret \
          docker-registry regcred \
          -n devops-test \
          --docker-server=https://index.docker.io/v1/ \
          --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
          --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
          --dry-run=client -o yaml | \
            kubectl apply -f -

    - name: "Deploy - Helm Package & Upgrade"
      run: |
        kubectl config get-contexts
        helm package --app-version=${{ github.sha }} .
        helm upgrade \
          -i devops-test-backend './devops-test-backend-0.0.0.tgz' \
          -n devops-test \
          --timeout 45m0s \
          --wait \
          --set replicaCount=3 \
          --set image=${{ secrets.DOCKERHUB_USERNAME }}/devops-test:backend-${{ github.sha }}
      working-directory: 'ops/k8s/backend'

  cleanup:
    name: "Cleanup Artifacts if main branch"
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    needs: [backend_kubernetes_deploy]
    steps:
    - name: "Delete Artifact"
      uses: geekyeggo/delete-artifact@v2
      with:
        name: myimage
